
export const UPDATE_READY = 'UPDATE_READY';
export const UPDATE_PLAYERS_LIST = 'UPDATE_PLAYERS_LIST';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const UPDATE_PLAYER_INFO = 'UPDATE_PLAYER_INFO';
